# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
COPY . .

# STEP4-4では以下は変更しない
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9000" ]